export { default as Home } from "./home/Home";
export { default as Contact } from "./contact/Contact";
export { default as Admin } from "./admin/Admin";
export { default as Cart } from "./cart/Cart";
export { default as Auth } from "./auth/Auth";
export { default as Reset } from "./reset/Reset";
export { default as Checkout } from "./checkout/Checkout";
export { default as ProductDetails } from "./productDetails/ProductDetails";
export { default as Shop } from "./shop/Shop";
